{% set version = "3.10.5" %}

package:
  name: xorjson
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xorjson/xorjson-{{ version }}.tar.gz
  sha256: f23d792ee3092d60bb9f772eacf14df5484cfb25cd8874693bde83987254c193

build:
  number: 2
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1,<2                      # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ stdlib("c") }}                   # [not win]
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=1,<2
  run:
    - python

test:
  imports:
    - xorjson
  requires:
    - pip
    - mypy
  commands:
    - pip check
    - mypy -m xorjson

about:
  home: https://github.com/timkpaine/xorjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: xorjson, a fork of orjson, is a fast, correct JSON library for Python.
  doc_url: https://github.com/timkpaine/xorjson
  dev_url: https://github.com/timkpaine/xorjson

extra:
  recipe-maintainers:
    - timkpaine
